@startuml Diagrama_de_Classses_KlimaX
        class Filme {
                +Integer filmeid
                +String titulo
                +String poster
                +Dict genero
                +Float mediavotos
                +Integer numvotos

                +__init__()
                +to_dict()
        }

        class Detalhes{
                +Dict elenco
                +Dict streaming
                +String sinopse


        }

        class Elenco{

                +List<Ator> atores
                +__init__()
        }

        class Ator {
                +String nome
                +Integer id
                +String imagem
                +__init__()
        }

        class Usuario {
                +List favoritos
                +List assistidos


                +__init__()
        }
        class FilmeIdeal {
                +Dict genero
                +Dict elenco
                +Integer id

                +__init__()
                +filmemodelo()
                +filmesimilar()
        }

        class DetalhesUsuario extends Usuario {
                +List generosFavoritos
                ...
                +List favoritos
                +List assistidos


        }

        FilmeIdeal -> Detalhes
        Detalhes -|> Filme
        Elenco <-- Detalhes
        Ator <- Elenco

@enduml
