@startuml Diagrama_de_Classses_KlimaX
        class Filme {
                +Integer filmeid
                +String titulo
                +String poster
                +Dict genero
                +Float mediavotos
                +Integer numvotos

                +__init__()
                +to_dict()
        }

        class Detalhes{
                +Dict cast
                +Dict streaming
                +String sinopse


        }

        class Elenco{

                +List<Ator> atores
                +__init__()
        }

        class Ator {
                +String nome
                +Integer id
                +String imagem
                +__init__()
        }

        class Usuario {

                +String nome
                +String nome_de_usuario
                +Integer idade
                +String emai
                +List favoritos
                +List assistidos
                +avaliarFilme(Filme filme, Integer nota)

                +String nomeUsuario
                +String email
                +String senha

                +__init__()
        }
        class FilmeIdeal {
                +Dict genero
                +Dict elenco
                +Integer id

                +__init__()
                +filmemodelo()
                +filmesimilar()
        }

        class DetalhesUsuario extends Usuario {
                +List generosFavoritos

                ...

                +String nome
                +Integer idade
                +List favoritos
                +List assistidos


        }

        FilmeIdeal -> Detalhes
        Detalhes -|> Filme
        Elenco <-- Detalhes
        Ator <- Cast

@enduml
